CC = gcc
CFLAGS = -O2 -Wall
LDFLAGS = -lGLESv2 -lEGL
INCLUDES = -I/usr/include/GLES3 -I/usr/include/EGL

TARGET = egl_test

$(TARGET): egl_test.c
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $< $(LDFLAGS)

clean:
	rm -f $(TARGET)
